server:
  port: 9001

spring:
               
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411    
  config:
    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/olx-login-monitor"
  endpoint:
    shutdown:
      enabled: false

    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost