server:
   port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nallamothuranganath/olx-config
          default-label: main
          username: nallamothuranganath
          password: welcome@5026
          clone-on-start: true