server:
  port: 9002

spring:

  application:
    name: masterdata-service
  zipkin:
    base-url: http://localhost:9411    
  config:
    import: configserver:http://localhost:8888  
  cloud:
    discovery:
      enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/olx-master-monitor"
  endpoint:
    shutdown:
      enabled: false
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost     